#!/usr/bin/env python
'''
This script is used to lease an IP address (or addresses). The IP (or IPs) will be used by an OpenNebula VM and should not be allocated to any other host in the network.

Arguments:

AddressRange and Address. The AddressRange (IP network) and address request in XML, encoded in Base 64. The XML will contain the AR as defined by the previous action; and the address request:
<IPAM_DRIVER_ACTION_DATA>
<AR>
  As returned by previous action, see above for examples.
</AR>
<ADDRESS>
  <SIZE> Number of IPs to allocate, in a continous range from the firs IP</SIZE>
</ADDRESS>
</IPAM_DRIVER_ACTION_DATA>
Request ID, used internally to identify this IPAM request.
Returns: This scrit MUST output the leased IP range as defined by the ADDRESS element in template format thourgh STOUT. For example, to lease IPs from 10.0.0.2 to 10.0.0.35 return:

ADDRESS = [ IP = "10.0.0.2", SIZE=34 ]
If the “size” IPs cannot be assgined the sript must return -1, otherwise it must exit 0.

'''
